# Generated by Django 4.2.11 on 2024-04-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_pacientes_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='password',
            field=models.CharField(max_length=16),
        ),
    ]
