# Generated by Django 4.2.11 on 2024-04-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_pacientes_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('sexo', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=100)),
                ('fechanac', models.DateField()),
                ('especialidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=16)),
                ('sexo', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=100)),
                ('fechanac', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservamedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctornombre', models.CharField(max_length=50)),
                ('doctoremail', models.EmailField(max_length=50)),
                ('pacientenombre', models.CharField(max_length=50)),
                ('pacienteemail', models.EmailField(max_length=50)),
                ('citamedicafecha', models.DateField(max_length=10)),
                ('citamedicahora', models.TimeField(max_length=10)),
                ('sintomas', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('prescripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
