# Generated by Django 4.2.11 on 2024-04-26 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_doctores_recepcionista_reservamedica'),
    ]

    operations = [
    ]
