# Generated by Django 5.0.3 on 2024-05-04 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20240426_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservamedica',
            name='prescripcion',
        ),
    ]
