# Generated by Django 5.0.3 on 2024-05-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_pacientes_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='password',
            field=models.CharField(max_length=16),
        ),
    ]
