# Generated by Django 5.0.3 on 2024-05-05 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_alter_pacientes_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recepcionista',
            new_name='Administrador',
        ),
    ]
